authors: [dobrakmato, Weefle]
database: false
main: eu.matejkormuth.pexel.PexelCore.PexelCore
name: pexel-core
startup: postworld
version: 1.1

commands:
   arena:
     description: Pouziva sa na pracu s arenami.
     aliases: [minigamearena, marena]
     usage: /arena <mode> <name> <action> [param1] [param2]
   lobbyarena:
     description: Pouziva sa na pracu s lobbynami.
     usage: /lobbyarena <action> <name> [param1] [param2]   
   qj:
     description: Pouziva sa na quick-join.
     aliases: [quickjoin, join]
     usage: /qj [game]
   friend:
     description: Pouziva sa na pracu s priatelmi.
     usage: /friend <playerName>
   unfriend:
     description: Pouziva sa na pracu s priatelmi.
     usage: /unfriend <playerName>
   party:
     description: Pouziva sa na pracu s priatelmi.
     aliases: [p]
     usage: /party <action> <playerName>
   gate:
     description: Pouziva sa na pracu s gates.
     aliases: [gates]
     usage: /gate <action> <actionType> <actionContent>
   settings:
     description: Pouziva sa na pracu s nastaveniami.
     aliases: [options, option, setting]
     usage: /settings <setting> <true/false>
   pcmd:
     description: PCMD
     usage: /pcmd
   spawn:
     description: Teleports player to spawn.
     aliases: [hub, lobby]
     usage: /spawn